# -*- coding: utf-8 -*-
"""Data mining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC6HiWGvOj62aJAPL6yu4eSuyy4kB0fP
"""

# =====================================================
# ENN EXPERIMENT ON WAVEFORM-NOISE DATASET
# =====================================================

# =====================================================
# 1. IMPORT LIBRARIES
# =====================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from imblearn.under_sampling import EditedNearestNeighbours


# =====================================================
# 2. LOAD DATASET
# =====================================================

file_path = 'waveform-+noise.data'

# Correctly read the data as comma-separated values
# The file contains 40 features and 1 target variable, all numeric.
# Using header=None as there are no explicit headers.
# Pandas should infer the comma delimiter, or we can explicitly set sep=','
df = pd.read_csv(file_path, header=None)

print("========== DATASET HEAD ==========")
print(df.head())
print()


# =====================================================
# 3. CONVERT TO BINARY CLASSIFICATION (NOT NEEDED FOR THIS DATASET)
#    The target is already in the last column and appears to be multi-class.
# =====================================================


# =====================================================
# 4. DEFINE FEATURES AND LABELS
# =====================================================

X = df.iloc[:, :-1]  # All columns except the last one as features
y = df.iloc[:, -1]   # The last column as the target variable

print("========== CLASS DISTRIBUTION =========")
print(y.value_counts().sort_index()) # Print sorted class distribution
print()


# =====================================================
# 5. TRAIN / TEST SPLIT
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    stratify=y,
    random_state=42
)

print("========== TRAIN / TEST SIZE ==========")
print("Train Size:", X_train.shape)
print("Test Size :", X_test.shape)
print()


# =====================================================
# 6. STANDARDIZATION
# =====================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)


# =====================================================
# 7. BASELINE MODEL (WITHOUT ENN)
# =====================================================

print("========================================")
print("BASELINE MODEL (WITHOUT ENN)")
print("========================================")

k_neighbors_baseline = 5 # Changed n_neighbors to a variable
knn_baseline = KNeighborsClassifier(n_neighbors=k_neighbors_baseline)

knn_baseline.fit(X_train_scaled, y_train)

y_pred_baseline = knn_baseline.predict(X_test_scaled)

baseline_accuracy = accuracy_score(y_test, y_pred_baseline)

baseline_precision = precision_score(
    y_test,
    y_pred_baseline,
    average='weighted' # Adjusted for multi-class
)

baseline_recall = recall_score(
    y_test,
    y_pred_baseline,
    average='weighted' # Adjusted for multi-class
)

baseline_f1 = f1_score(
    y_test,
    y_pred_baseline,
    average='weighted' # Adjusted for multi-class
)

print(f"Accuracy : {baseline_accuracy:.4f}")
print(f"Precision: {baseline_precision:.4f}")
print(f"Recall   : {baseline_recall:.4f}")
print(f"F1-score : {baseline_f1:.4f}")
print()

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred_baseline))
print()

print("Classification Report")
print(classification_report(y_test, y_pred_baseline))
print()


# =====================================================
# 8. ENN EXPERIMENTS
# =====================================================

enn_values = [3, 5, 7]
k_neighbors_enn = 5 # Setting n_neighbors for KNN after ENN

for k in enn_values:

    print("========================================")
    print(f"ENN EXPERIMENT - k (for ENN) = {k}")
    print("========================================")

    # =================================================
    # APPLY ENN ONLY ON TRAIN SET
    # =================================================

    enn = EditedNearestNeighbours(
        n_neighbors=k
    )

    X_train_enn, y_train_enn = enn.fit_resample(
        X_train_scaled,
        y_train
    )

    # =================================================
    # SAMPLE ANALYSIS
    # =================================================

    before_samples = len(y_train)

    after_samples = len(y_train_enn)

    removed_samples = before_samples - after_samples

    print("========== SAMPLE ANALYSIS ==========")

    print("Before ENN:", before_samples)

    print("After ENN :", after_samples)

    print("Removed   :", removed_samples)

    print()

    # =================================================
    # CLASS ANALYSIS
    # =================================================

    original_class = pd.Series(y_train).value_counts().sort_index()
    enn_class = pd.Series(y_train_enn).value_counts().sort_index()

    print("========== REMOVED SAMPLES BY CLASS ==========")
    for class_label in original_class.index:
        removed_count = original_class.get(class_label, 0) - enn_class.get(class_label, 0)
        print(f"Removed Class {class_label}: {removed_count}")
    print()

    # =================================================
    # TRAIN KNN AFTER ENN
# =================================================

    knn_enn = KNeighborsClassifier(
        n_neighbors=k_neighbors_enn
    )

    knn_enn.fit(
        X_train_enn,
        y_train_enn
    )

    y_pred_enn = knn_enn.predict(
        X_test_scaled
    )

    # =================================================
    # EVALUATION METRICS
    # =================================================

    accuracy = accuracy_score(
        y_test,
        y_pred_enn
    )

    precision = precision_score(
        y_test,
        y_pred_enn,
        average='weighted' # Adjusted for multi-class
    )

    recall = recall_score(
        y_test,
        y_pred_enn,
        average='weighted' # Adjusted for multi-class
    )

    f1 = f1_score(
        y_test,
        y_pred_enn,
        average='weighted' # Adjusted for multi-class
    )

    print("========== PERFORMANCE ==========")

    print(f"Accuracy : {accuracy:.4f}")

    print(f"Precision: {precision:.4f}")

    print(f"Recall   : {recall:.4f}")

    print(f"F1-score : {f1:.4f}")

    print()

    print("========== CONFUSION MATRIX ==========")

    print(confusion_matrix(
        y_test,
        y_pred_enn
    ))

    print()

    print("========== CLASSIFICATION REPORT ==========")

    print(classification_report(
        y_test,
        y_pred_enn
    ))

    print()


# =====================================================
# 9. FINISH
# =====================================================

print("========================================")
print("EXPERIMENT FINISHED")
print("========================================")



"""### 4. Define Features and Labels for `df_waveform`"""

X_waveform = df_waveform.iloc[:, :-1]  # All columns except the last one as features
y_waveform = df_waveform.iloc[:, -1]   # The last column as the target variable

print("========== FEATURES HEAD (X_waveform) ==========")
print(X_waveform.head())
print("\n========== LABELS HEAD (y_waveform) ==========")
print(y_waveform.head())
print("\nFeatures shape:", X_waveform.shape)
print("Labels shape:", y_waveform.shape)

import matplotlib.pyplot as plt
import seaborn as sns

# Data collection from the previous experiment results
k_values = [3, 5, 7]
metrics = {
    'Accuracy': [0.7000, 0.6771, 0.6521],
    'Precision': [0.8122, 0.8493, 0.8689],
    'Recall': [0.5720, 0.4825, 0.4125],
    'F1-score': [0.6712, 0.6154, 0.5594]
}

# Plotting
plt.figure(figsize=(10, 6))
for metric_name, values in metrics.items():
    plt.plot(k_values, values, marker='o', label=metric_name)

plt.title('So sánh hiệu quả của ENN với các giá trị k khác nhau')
plt.xlabel('Giá trị k (Số hàng xóm)')
plt.ylabel('Giá trị chỉ số')
plt.xticks(k_values)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.show()

# =====================================================
# ENN EXPERIMENT ON WAVEFORM-NOISE DATASET
# =====================================================

# =====================================================
# 1. IMPORT LIBRARIES
# =====================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from imblearn.under_sampling import EditedNearestNeighbours


# =====================================================
# 2. LOAD DATASET
# =====================================================

file_path = 'waveform-+noise.data'

# Correctly read the data as comma-separated values
# The file contains 40 features and 1 target variable, all numeric.
# Using header=None as there are no explicit headers.
# Pandas should infer the comma delimiter, or we can explicitly set sep=','
df = pd.read_csv(file_path, header=None)

print("========== DATASET HEAD ==========")
print(df.head())
print()


# =====================================================
# 3. CONVERT TO BINARY CLASSIFICATION (NOT NEEDED FOR THIS DATASET)
#    The target is already in the last column and appears to be multi-class.
# =====================================================


# =====================================================
# 4. DEFINE FEATURES AND LABELS
# =====================================================

X = df.iloc[:, :-1]  # All columns except the last one as features
y = df.iloc[:, -1]   # The last column as the target variable

print("========== CLASS DISTRIBUTION ========")
print(y.value_counts().sort_index()) # Print sorted class distribution
print()


# =====================================================
# 5. TRAIN / TEST SPLIT
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    stratify=y,
    random_state=42
)

print("========== TRAIN / TEST SIZE ==========")
print("Train Size:", X_train.shape)
print("Test Size :", X_test.shape)
print()


# =====================================================
# 6. STANDARDIZATION
# =====================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)


# =====================================================
# 7. BASELINE MODEL (WITHOUT ENN)
# =====================================================

print("========================================")
print("BASELINE MODEL (WITHOUT ENN)")
print("========================================")

k_neighbors_baseline = 5 # Changed n_neighbors to a variable
knn_baseline = KNeighborsClassifier(n_neighbors=k_neighbors_baseline)

knn_baseline.fit(X_train_scaled, y_train)

y_pred_baseline = knn_baseline.predict(X_test_scaled)

baseline_accuracy = accuracy_score(y_test, y_pred_baseline)

baseline_precision = precision_score(
    y_test,
    y_pred_baseline,
    average='weighted' # Adjusted for multi-class
)

baseline_recall = recall_score(
    y_test,
    y_pred_baseline,
    average='weighted' # Adjusted for multi-class
)

baseline_f1 = f1_score(
    y_test,
    y_pred_baseline,
    average='weighted' # Adjusted for multi-class
)

print(f"Accuracy : {baseline_accuracy:.4f}")
print(f"Precision: {baseline_precision:.4f}")
print(f"Recall   : {baseline_recall:.4f}")
print(f"F1-score : {baseline_f1:.4f}")
print()

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred_baseline))
print()

print("Classification Report")
print(classification_report(y_test, y_pred_baseline))
print()


# =====================================================
# 8. ENN EXPERIMENTS
# =====================================================

enn_values = [3, 5, 7]
k_neighbors_enn = 5 # Setting n_neighbors for KNN after ENN

for k in enn_values:

    print("========================================")
    print(f"ENN EXPERIMENT - k (for ENN) = {k}")
    print("========================================")

    # =================================================
    # APPLY ENN ONLY ON TRAIN SET
    # =================================================

    enn = EditedNearestNeighbours(
        n_neighbors=k
    )

    X_train_enn, y_train_enn = enn.fit_resample(
        X_train_scaled,
        y_train
    )

    # =================================================
    # SAMPLE ANALYSIS
    # =================================================

    before_samples = len(y_train)

    after_samples = len(y_train_enn)

    removed_samples = before_samples - after_samples

    print("========== SAMPLE ANALYSIS ==========")

    print("Before ENN:", before_samples)

    print("After ENN :", after_samples)

    print("Removed   :", removed_samples)

    print()

    # =================================================
    # CLASS ANALYSIS
    # =================================================

    original_class = pd.Series(y_train).value_counts().sort_index()
    enn_class = pd.Series(y_train_enn).value_counts().sort_index()

    print("========== REMOVED SAMPLES BY CLASS ==========")
    for class_label in original_class.index:
        removed_count = original_class.get(class_label, 0) - enn_class.get(class_label, 0)
        print(f"Removed Class {class_label}: {removed_count}")
    print()

    # =================================================
    # TRAIN KNN AFTER ENN
# =================================================

    knn_enn = KNeighborsClassifier(
        n_neighbors=k_neighbors_enn
    )

    knn_enn.fit(
        X_train_enn,
        y_train_enn
    )

    y_pred_enn = knn_enn.predict(
        X_test_scaled
    )

    # =================================================
    # EVALUATION METRICS
    # =================================================

    accuracy = accuracy_score(
        y_test,
        y_pred_enn
    )

    precision = precision_score(
        y_test,
        y_pred_enn,
        average='weighted' # Adjusted for multi-class
    )

    recall = recall_score(
        y_test,
        y_pred_enn,
        average='weighted' # Adjusted for multi-class
    )

    f1 = f1_score(
        y_test,
        y_pred_enn,
        average='weighted' # Adjusted for multi-class
    )

    print("========== PERFORMANCE ==========")

    print(f"Accuracy : {accuracy:.4f}")

    print(f"Precision: {precision:.4f}")

    print(f"Recall   : {recall:.4f}")

    print(f"F1-score : {f1:.4f}")

    print()

    print("========== CONFUSION MATRIX ==========")

    print(confusion_matrix(
        y_test,
        y_pred_enn
    ))

    print()

    print("========== CLASSIFICATION REPORT ==========")

    print(classification_report(
        y_test,
        y_pred_enn
    ))

    print()


# =====================================================
# 9. FINISH
# =====================================================

print("========================================")
print("EXPERIMENT FINISHED")
print("========================================")